server:
  port: 8080
  error:
    include-message: always

aws:
  accessKeyId: your-access-key-id
  secretAccessKey: your-secret-access-key
  region: ap-southeast-2
  s3:
    buckets:
      customer: uobkh-intranet
